### ISSUE TITLE
I can't find the menu

### ISSUE THREAD

**Issue by gnumoksha** [inpsyde/search-and-replace#73] opened 2017-01-05 18:22 UTC
I've installed the plugin through zip and wpackagist.org, on my multisite WordPress.  After that, I've activated the plugin on the plugins page and menu `Tools` -> `Search & Replace` did not appear.

**Comment by gnumoksha** [comment] 2017-01-05 18:32
This issue has occurred because of the following in my wp-config.php:
```
define( 'DISALLOW_FILE_MODS', true );
```

An alert during the plugin activation will be nice.

**Comment by derpixler** [comment] 2017-01-05 18:53
Hi, the Issue is, we have no Multisite menu under the Network Panel. You will find it under Blog 1.

But thanks for reporting we solve this.

**Comment by bueltge** [comment] 2017-06-15 07:25
@devbanana Can you valid this please, thx!

**Comment by benosman** [comment] 2017-07-01 17:08
I ran into this myself, though i'm not using multi site.

However, I do have the same ```DISALLOW_FILE_MODS``` directive set, because I like to add plugins locally then deploy to the server using capistrano.

After some investigation I found it's because you are using the ```install_plugins``` capability here:

https://github.com/inpsyde/search-and-replace/blob/master/inc/Page/Manager.php#L66

A more suitable capability might be ```activate_plugins``` or ```manage_options```

**Comment by devbanana** [comment] 2017-08-28 12:50
@benosman Have you tried changing that value for yourself, and has it worked? I'm not too familiar with the DISALLOW_FILE_MODS constant.

**Comment by widoz** [comment] 2017-12-09 08:55
I tried in a multisite installation with the `define( 'DISALLOW_FILE_MODS', true );` but no problems, the menu link is available under the `Tools` menu within the site where the plugin is activated.

I'm referencing to the master code.

**Comment by widoz** [comment] 2017-12-19 09:38
I'm closing this since the problem seems not appear anymore. 

@benosman Feel free to open it again if needed.

**Comment by dlong500** [comment] 2018-07-17 19:55
I still have this issue trying to use the master branch.  It simply doesn't show up at all.  I'd love to use this plugin but I can't do something as simple as replace http with https using the published version 3.1.2 because of the "Your search contains your current site url" issue.

**Comment by bueltge** [comment] 2018-07-19 06:32
Hi @dlong500 
can you explain the experience so that we understand how you install, how you use.
It is a single or multisite install? Have you constants defined in the wp-config.php or vie plugin that change the default of the installation?
Have you only the problem on s/r http to https. The check for the domain was a javascript problem that I removed. It was included in the older version to supports users, there have not enough knowledge to use it.

**Comment by dlong500** [comment] 2018-07-19 07:31
This is a single site install.  There are no special changes in the wp-config.php file, nor do I believe there to be any other things that would alter a standard WordPress install.

The site is running https for everything.  I'm not getting any errors (during or after the plugin activation).  It just simply doesn't show up in the tools menu.

**Comment by widoz** [comment] 2018-09-09 06:58
Hi @dlong500,

Sorry for the long wait, if you are using the clone from the master you want probably execute `composer install --no-dev` to have at least the autoloader, otherwise the plugin will stop work at this line https://github.com/inpsyde/search-and-replace/blob/master/inpsyde-search-replace.php#L83 during the bootstrap phase.

Let us know.

**Comment by mattcroftuk** [comment] 2018-10-10 14:29
After installing this plugin into a bedrock setup i am not seeing the menu item under Tools to navigate here, was there a valid solution to fixing this?

**Comment by bvdv** [comment] 2018-11-17 12:35
> After installing this plugin into a bedrock setup i am not seeing the menu item under Tools to navigate here, was there a valid solution to fixing this?

I tried S&R master branch and 3.1.2 version with last version of Bedrock 1.9.0 and Sage 9.0.5. In all cases no problem, S&R link is available in Tools menu.

**Comment by bueltge** [comment] 2018-11-22 08:50
Currently we have different tests, always without issues, problem so that I close them. Feel free to open a new ticket with a valid description to retrace the problem. Thanks for understanding.

**Closed by bueltge** 2018-11-22 08:50 UTC
Labels: bug
